### ISSUE TITLE
Styling for book-summary-tile

### ISSUE THREAD

**Issue by anhvoleduy** [DevDay2019-AxonActive/DevDay2019-Micro-Frontends#3]
Component **book-summary-tile** was build but it's not styled yet.
Update **book-summary-tile**'s css file to make it follow the mockup.
Note; don't need to be exactly the same with the mockup. Just need to be good-looking

Reference:
https://github.com/DevDay2019-AxonActive/DevDay2019-Micro-Frontends/tree/master/project/angular/src/app/book-summary-tile

**Comment by LinhTH** [comment]
Hi @truongsinh96, kéo task sang làm đi em ơi :)
