### ISSUE TITLE
Setup Front-End server for Showcase

### ISSUE THREAD

**Issue by anhvoleduy** [DevDay2019-AxonActive/DevDay2019-Micro-Frontends#9]
Server 1 :
              IP : 85.214.44.228
              Team owner : Team 1 + Team 2
              SSH account : team1/Te@111!DevDayAxon2019
                                        team2/Te@111@DevDayAxon2019
 
Server 2 :
              IP : 85.214.44.178
              Team owner : Team 3 + Team 4
              SSH account : team3/ Te@111#DevDayAxon2019
                                        team4/ Te@111$DevDayAxon2019
 
Server 3 :
              IP : 85.214.44.79
              Team owner : Team 5 + Team 6
              SSH account : team5/ Te@111%DevDayAxon2019
                                        team6/ Te@111^DevDayAxon2019
 
*Note : all of command executed have to be used with sudo for preventing any restricted privileged.

**Comment by LinhTH** [comment]
@anhvoleduy ủa anh Tân có nhận task này ko?

**Comment by anhvoleduy** [comment]
@LinhTH Để e hỏi a Tân
